In [1]:
import numpy as np
print(np.__version__)

2.1.1


In [2]:
a = np.array([1,2,3])

In [3]:
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a[0])
a[0]=10
print(a)

[1 2 3]
(3,)
int64
1
3
8
1
[10  2  3]


In [4]:
b_t=[[1,2,5],[3,4,5],[5,6,7]]
b=np.array(b_t)
print(b)
print(b.shape)
print(b.size)

[[1 2 5]
 [3 4 5]
 [5 6 7]]
(3, 3)
9


In [5]:
c= a* np.array([2,2,0])
print(c)
print(c.shape)

[20  4  0]
(3,)


In [6]:
l=[1,2,3]
a = np.array([1,2,3])
# l.append(4)
# l=l+[5]
# a=a+ np.array([4])
# l=l*[5]
a=a*np.array([5])
print(l)
print(a)

[1, 2, 3]
[ 5 10 15]


In [7]:
# dot product using list
l1=[1,2,3]
l2=[4,5,6]
dot  =0 
for i in range(len(l1)):
    dot+=l1[i]*l2[i]

print(dot)

32


In [8]:
# dot product using array 
a1=np.array(l1)
a2=np.array(l2)
dot2=np.dot(a1,a2)
print(dot2)

32


In [9]:
dot1=(a1*a2).sum()
dot2= a1 @ a2
print(dot1,dot2)

32 32


In [10]:
#  multidimentinal arrays
mda= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mda)
print(mda.shape)

print(mda[0])
print(mda[0][0])
print(mda[0,0])
print(mda.T)
print(np.linalg.inv(mda))
print(np.linalg.det(mda))
c=np.diag(mda)
print(c)
print(np.diag(c))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3]
1
1
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
6.66133814775094e-16
[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [11]:
# slicing arrays
mda= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mda)

b=mda[0,1]
print(b)

# row 0
print(mda[0,1:3])
# colums
print(mda[:,1])
# boolean index
bool_indx=mda>4
print(bool_indx)
# print(sum(sum(bool_indx)))
print(mda[bool_indx])

b=np.where(mda>4,mda,None)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[2 3]
[2 5 8]
[[False False False]
 [False  True  True]
 [ True  True  True]]
[5 6 7 8 9]
[[None None None]
 [None 5 6]
 [7 8 9]]


In [12]:
# fansy indexing
a=np.array([10,19,30,41,50,61])
print(a)
b=[1,3,5]
print(a[b])


[10 19 30 41 50 61]
[19 41 61]


In [13]:
# finding even ideicies
even=np.argwhere(a%2==0).flatten()
print(a[even])

[10 30 50]


In [26]:
# reshaping arrays 
a = np.arange(1,7)
print(a)
print(a.shape)
b=a.reshape((2,3))
print(b)
# new axis
c=a[np.newaxis,:]
print(c)
print(c.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
(1, 6)


In [32]:
# concatinating
a= np.array([[1,2],[3,4]])
print("a:",a)
b=np.array([[5,6]])
print("b:",b)
c=np.concatenate((a,b))
print(c)
d=np.concatenate((a,b.T),axis=1)
print(d)

a: [[1 2]
 [3 4]]
b: [[5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [33]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
# hstack
c=np.hstack((a,b))
print(c)
d=np.vstack((a,b))
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# broadcasting
# it allows np to work woth rray of different shapes in various math operations

x=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
a=np.array([1,0,1])
y=x+a
print(y)


[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


In [42]:
# functions and axis
a=np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)
print(a.sum())
print(a.sum(axis=None))
print(a.sum(axis=0)) #column wise sum
print(a.sum(axis=1)) #row wise sum
print(a.mean(axis=1)) #row wise meam
print(a.mean(axis=0)) #column wise meam
print(a.mean(axis=None)) #overall wise meam
print(a.var(axis=None)) #varience
print(a.std(axis=None)) #standard deviaton
print(a.min(axis=None)) #min val
print(a.max(axis=None)) #max val



[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
210
210
[24 26 28 30 32 34 36]
[ 70 140]
[10. 20.]
[12. 13. 14. 15. 16. 17. 18.]
15.0
29.0
5.385164807134504
7
23


In [47]:
# datatypes
x=np.array([1,2])
print(x)
print(x.dtype)
x=np.array([1.0,2,0])
print(x)
print(x.dtype)
x=np.array([1.0,2.0], dtype=np.int64)
print(x)
print(x.dtype)
x=np.array([1.0,2.0], dtype=np.int32)
print(x)
print(x.dtype)

[1 2]
int64
[1. 2. 0.]
float64
[1 2]
int64
[1 2]
int32


In [56]:
# copying arrays
a= np.array([1,2,3])
b=a
c=a.copy()
b[0]=42
c[1]=53
print(a)
print(b)
print(c)


[42  2  3]
[42  2  3]
[ 1 53  3]


In [61]:
# generating arrays
a=np.zeros((2,3))
print(a)
b=np.ones((2,3))
print(b)

c=np.full((2,3),5.0)
print(c)
d=np.eye(3)
print(d)

e=np.arange(20)
print(e)

f=np.linspace(0,10,3)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.  5. 10.]


In [76]:
# random numbers
a=np.random.random((3,2)) # randome number betwen 0-1
print(a)
b=np.random.randn(3,2)#noraml/gaussian distrubtuon
print(b)
print(b.mean(),b.var())
c=np.random.randint(10,size=(3,3))
print(c)
d=np.random.choice([-8,-7,-6],size=(3,3))
print(d)

[[0.84966871 0.57932263]
 [0.3253745  0.4021517 ]
 [0.55635076 0.48468605]]
[[-0.54908318  1.19620653]
 [-0.11480081 -1.5804177 ]
 [-0.70306867  1.40218312]]
-0.05816345117625602 1.1139044749961189
[[1 0 3]
 [4 3 0]
 [6 7 6]]
[[-7 -8 -7]
 [-6 -6 -8]
 [-7 -8 -8]]


In [ ]:
# linear algebra (linag module)

a=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors) #column vector

# e_vec*E_val=A*e_vec
b=eigenvectors[:,0]*eigenvalues[0]
print(b)
c=a @ eigenvectors[:,0]
print(c)
print(np.allclose(b,c))






[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
True


In [85]:
# solving linear eq with np
# x1 + x2 = 2200
# 1.5 x1 + 4.0 x2 = 5050
# X=[[x1],[x2]] A=[[1,1],[1.5,4.0]] B=[[2200],[5050]]

#manual method

A=np.array([[1,1],[1.5,4.0]])
B=np.array([[2200],[5050]])

x=(np.linalg.inv(A)) @ B
print(x)

# linalg solve function
x=np.linalg.solve(A,B)
print(x)

[[1500.]
 [ 700.]]
[[1500.]
 [ 700.]]


In [88]:
# loading csv files
# np.loadtxt and np.genfromtxt

data= np.loadtxt('spambase.csv', delimiter=',', dtype=np.float32)
print(data.shape)
data2=np.genfromtxt('spambase.csv',delimiter=',',dtype=np.float32)
print(data2.shape)

(4601, 58)
(4601, 58)
